---
galaxy_info:
  role_name: node_feature_discovery
  author: Ansible Automation
  description: Install and configure Node Feature Discovery Operator
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - openshift
    - kubernetes
    - gpu
    - hardware

dependencies: []
