---
galaxy_info:
  author: Ansible Automation
  description: Deploy KServe models with vLLM runtime
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - openshift
    - ai
    - kserve
    - vllm
    - llm

dependencies: []
